name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/coverage-final.json
          flags: script,${{ matrix.os }}
          name: codecov-script
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
