name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Install dependencies
        run: npm install
      - name: Installing Jest
        run: npm install jest --save-dev
      - name: Install pytest
        run: pip install pytest
      - name: Install pytest coverage
        run: pip install pytest-cov
      - name: Grant permission acces to all users
        run: chmod +x node_modules/.bin/jest
      - name: Save coverage file
        run: pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/coverage-final.json
          name: codecov-script
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
